version: '3.1'

services:

    proxy:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro

    api:
        build: .
        image: readapi:1.0
        ports:
            - 5000:5000
        restart: always
